### ISSUE TITLE
`<TransitionGroup />` incorrectly updates children

### ISSUE THREAD

**Issue by muratmavlidov** [Ayub-Begimkulov/react-transition#22]
Привет!

Столкнулся с проблемой обновления списка элементов, обернутого в Transition. Опишу кейс: 

1. Сначала оборачиваем функцию рендера элементов в **TransitionGroup** 

`<TransitionGroup name="fade">{list.map(renderItem)}</TransitionGroup>`

2. Затем опишем функцию, которая возвращает элемент обернутый в **Transition**

```
const renderItem = (item) => (
   <Transition key={item.id}>
     <li key={item.id}>
       {item.a} - {item.b}
     </li>
   </Transition>
 );
```

Если list это массив элементов, каждый из которых является объектом, который содержит в себе  id и прочие свойства, то при обновлении листа Transition будет либо _мешать_ перерендеру, в случае если не был обновлен id (или свойство, которое было ему передано в качестве **key**), либо _воспроизводить анимацию_, даже если порядок элементов не был изменен.

Воспроизвел пример тут => [CodeSandbox](https://codesandbox.io/s/nostalgic-buck-cl1ih?file=/src/App.js)

**Comment by Ayub-Begimkulov** [comment]
## Translation to English:

Hey!

Faced the problem of updating the list of items wrapped in Transition. Here is the case:

1. First, we wrap the element render function in a **TransitionGroup**.

`<TransitionGroup name="fade">{list.map(renderItem)}</TransitionGroup>`

2. Then we will describe a function that returns an element wrapped in a **Transition**

```js
const renderItem = (item) => (
   <Transition key={item.id}>
     <li key={item.id}>
       {item.a} - {item.b}
     </li>
   </Transition>
 );
```

If a **list** is an array of elements, each of which is an object that contains an id and other properties, then when the sheet is updated, the Transition will either interfere with the rerender if the id has not been updated (or the property that was passed to it as **key**) or plays the animation even if the order of the elements has not been changed.

Reproduced the example here => [CodeSandbox](https://codesandbox.io/s/nostalgic-buck-cl1ih?file=/src/App.js)
